name: Self Hosted Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Runner Machine
        run: hostname

      - name: Print Message
        run: echo "Self Hosted Runner Working Successfully"

      - name: Show Current Folder
        run: pwd

      - name: System Info
        run: |
          hostname
          whoami
          ipconfig